server:
    port: 8090
    session:
        timeout: 30

spring:
    datasource:
        druid:
            url: jdbc:mysql://localhost:5566/study?characterEncoding=utf8&serverTimezone=UTC&useSSL=true
            username: root
            password: root
            driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        show-sql: true
        database: mysql