#https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
server:
    port: 8090
    session:
        timeout: 30

publickey: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJID+BF5h+byvfJZ/RCYluujbiktVaF70KaVXt5nupLX4TJle8ztmEXs+s9XkcmUc2F23dTA0cD6DL0zvR67FOMCAwEAAQ=="

spring:
    datasource:
        druid:
            url: "jdbc:mysql://localhost:5566/study?characterEncoding=utf8&serverTimezone=UTC&useSSL=true"
            username: "root"
            #password: "root"
            #加密后的密码
            password: "FbeFITOSglSx32BRRrGupaN+zOrMqWr6dP9vLyftbVXEf0bPVlsvND+a2IX7Ol+2Om03DL+BbUF25o7O3XGm2A=="
            driver-class-name: "com.mysql.cj.jdbc.Driver"
            #启动ConfigFilter
            filter:
                config:
                    enabled: true


            #配置 connection-properties，启用加密，配置公钥。
            connection-properties: config.decrypt=true;config.decrypt.key=${publickey}

            # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
            web-stat-filter:
                enabled: true
                url-pattern: "/*"
                exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
                session-stat-enable: true

            # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
            stat-view-servlet:
                enabled: true
                url-pattern: "/druid/*"
                reset-enable: false
                login-username: "admin"
                login-password: "admin"
                allow: "127.0.0.1"
                deny: "127.0.0.2"

    jpa:
        show-sql: true
        database: mysql
        hibernate:
          ddl-auto: "update"

    #
    thymeleaf:
        #开启模板缓存（默认值：true）
        cache: false
        #在构建URL时添加到视图名称前的前缀（默认值：classpath:/templates/）
        prefix: "classpath:/templates/"
        #在构建URL时添加到视图名称后的后缀（默认值：.html）
        suffix: ".html"
        #渲染之前检查模板是否存在（默认值:true）
        check-template: true
        #检查模板位置是否正确（默认值:true）
        check-template-location: true
        #开启MVC Thymeleaf视图解析（默认值：true）
        enabled: true
        #模板编码（默认值：UTF-8）
        encoding: "utf-8"
        #要运用于模板之上的模板模式。另见StandardTemplate-ModeHandlers(默认值：HTML5)
        mode: "HTML5"
        #Content-Type的值（默认值：text/html）
        content-type: "text/html"
        #要被排除在解析之外的视图名称列表，用逗号分隔
        excluded-view-names:
        #可解析的视图名称列表，用逗号分隔
        view-names:
        #Thymeleaf模板解析器在解析器链中的顺序。默认情况下，它排第一位。顺序从1开始，只有在定义了额外的TemplateResolver Bean时才需要设置这个属性。
        template-resolver-order:

    redis:
        # Redis数据库索引（默认为0）
        database: 0
        # Redis服务器地址
        host: "127.0.0.1"
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password:
        pool:
            # 连接池最大连接数（使用负值表示没有限制）
            max-active: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-wait: -1
            # 连接池中的最大空闲连接
            max-idle: 8
            # 连接池中的最小空闲连接
            min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0
